
:url=http://jobticket.hopou.com
:form = Content-Type: application/x-www-form-urlencoded
:xtoken=X-Token: d5dffc24691bb402fa12f18b7479425bce923588


#
POST :url/apps/user/login.html
:form
username=tiszy
password=asdasd1

#
GET :url/apps/user/get_department_list.html?parent_id=0&limit=1
:xtoken

#
GET :url/apps/user/get_contractor_list.html
:xtoken

#
GET :url/apps/user/get_operator_list.html?name=\u4e00\u7ea7\u90e8\u95e801&department_id=1
:xtoken

#
GET :url/apps/user/get_operator_list.html?name=\u627f\u5305\u55462223&contractor_id=1
:xtoken

#
POST :url/apps/user/change_pwd.html
:form
:xtoken
old_pwd=asdasd2
new_pwd=asdasd1
