
:url=http://jobticket.hopou.com
:form = Content-Type: application/x-www-form-urlencoded
:xtoken=X-Token: d5dffc24691bb402fa12f18b7479425bce923588


#
POST :url/apps/user/login.html
:form
username=tiszy
password=asdasd1

#
GET :url/apps/user/get_department_list.html?parent_id=0&limit=1
:xtoken

#
GET :url/apps/user/get_contractor_list.html
:xtoken

#
GET :url/apps/user/get_operator_list.html
:xtoken

#
GET :url/apps/user/get_operator_list.html?name=u627fu5305u55462223&contractor_id=1
:xtoken

#
POST :url/apps/user/change_pwd.html
:form
:xtoken
old_pwd=asdasd2
new_pwd=asdasd1

#
GET :url/apps/statistic/index.html
:xtoken

#
GET :url/apps/ticket/get_list.html?pageType=audit&type_id=1&page=1&limit=10
:xtoken

#获取作业票详情
GET :url/apps/ticket/get_info.html?ticket_id=45
:xtoken

#获取审批阶段意见+签字项
GET :url/apps/ticket/getTicketOpinions.html?ticket_id=45
:xtoken

#获取气体类型
GET :url/base_api/getSensorDataType.html
:xtoken

#提交安全措施审核项
POST :url/apps/ticket/set_checkres.html
:xtoken
ticket_id=45
sign=""
check_res[0][id]=1
check_res[0][res]=0
check_res[1][id]=2
check_res[1][res]=0
add_check_res[0][id]=1
add_check_res[0][res]=0

#上传图片
POST :url/apps/ticket/uploadImages.html
:xtoken
Content-Type: multipart/form-data
< ~/Pictures/bird.jpg

#添加气体数据
POST :url/apps/ticket/add_gas_data.html
:xtoken
ticket_id=45
gas_type_id=4
gas_type_name=二氧化硫SO2
concentration=29.9
unit_type=3
unit_name=%VOL
standard=30.8
group_id=1
group_name=有毒有害气体
place=部位0003
analysis_time=2023-05-15 10:30:11
analysis_user=现场人员003

#
POST :url/apps/ticket/del_gas_data.html
:xtoken
gas_data_id=5

#气体数据列表
GET :url/apps/ticket/get_gas_data_list.html?ticket_id=45
:xtoken

#获取气体数据选项
GET :url/apps/ticket/getGasTableOptions.html
:xtoken

#获取审批阶段意见+签字项
GET :url/apps/ticket/getTicketOpinions.html?ticket_id=58
:xtoken

#
GET :url/console/face_manage/get_list.html?org_id=1
:xtoken

#完工验收提交
POST :url/apps/ticket/set_accept.html
:xtoken
ticket_id=45
content=asdasd
sign=

#
POST http://httpbin.org/post
name=jocoo

